In [2]:
import numpy as np

In [3]:
list1=[1,2,3,4,5]
n1=np.array(list1)
list1

[1, 2, 3, 4, 5]

In [7]:
type (n1)

numpy.ndarray

In [9]:
matrix1=np.zeros((5,5))
matrix1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
matrix2=np.zeros((10,15))
matrix2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
########     Initialize NumPy array with some other number

In [13]:
matrix3 = np.full((5,5),69)
matrix3

array([[69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69]])

In [ ]:
# NumPy arrays

In [16]:
arr1=np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr1=np.arange(1,10,2)
arr1

array([1, 3, 5, 7, 9])

In [ ]:
#initialize array with random numbers 

In [19]:
random_array = np.random.randint(1,20,5)
random_array

array([16,  7,  3,  9,  9], dtype=int32)

In [26]:
matrix=np.array([[1,2,3],[4,5,6]])
matrix.shape

(2, 3)

In [27]:
matrix.shape = (3,2)
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
################### JOINING NumPy ARRAYS

In [29]:
#Vertical Stack
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.vstack((n1,n2))


array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
#Horizontal Stack
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [32]:
#Column Stack
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#Creating 2 2-D matrices and summing them up:

In [43]:
mat1=np.full((3,3),10)
mat1=mat1+1
mat2=np.full((3,3),20)
mat2=mat2+2
np.sum([mat1,mat2])

np.int64(297)

In [44]:
np.sum([mat1,mat2],axis=0) 

array([[33, 33, 33],
       [33, 33, 33],
       [33, 33, 33]])

In [45]:
np.sum([mat1,mat2],axis=1)

array([[33, 33, 33],
       [66, 66, 66]])

In [48]:
#  MEAN
n1=np.arange(1,20)
np.mean(n1)

np.float64(10.0)

In [51]:
#    Median
n1=np.random.randint(1,800,10)
np.median(n1)

np.float64(324.5)

In [50]:
#   Standard Deviation
n1=np.arange(1,20)
np.std(n1)

np.float64(5.477225575051661)